# Don't build any extra formats
formats:
    - none
conda:
    file: ci/rtd_env.yml
python:
  version: 3.8
  setup_py_install: true
  install:
    - method: pip
      path: .
    - method: setuptools
      path: package
