beam_paths:
    0 : !AnalyticBeam
        class: UniformBeam
# TODO: check this: taken from https://mwatelescope.github.io/mwa_hyperdrive/defs/coords.html
telescope_location: (0.6875, 24.433, 0)
world: 'moon'
telescope_name: apollo11
