name: External Tests
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  pyuvsim:
    name: herasim
    runs-on: ubuntu-latest
    defaults:
      run:
        # Adding -l {0} helps ensure conda can be found properly.
        shell: bash -l {0}
    env:
      PYTHON: "3.12"

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: mpi4py/setup-mpi@f200dce75b64188be849b46657dcf86c721937b2 # v1.4.3

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON }}

      - name: Install pyuvsim
        run: |
          pip install --upgrade pip
          pip install .

      - name: clone hera_sim
        run: |
          cd ../
          git clone https://github.com/HERA-Team/hera_sim.git

      - name: Install hera_sim
        run: |
          cd ../hera_sim
          pip install --group tests .

      # re-install pyuvsim last to ensure the checked out code is installed
      # (because sometimes the hera_sim install overwrites the earlier install.)
      # keep the earlier install because it ensures the right dependencies are grabbed.
      - name: Install pyuvsim
        run: |
          cd ../pyuvsim
          pip install .
          cd ../hera_sim

      - name: Environment Info
        run: |
          pip list
          PYVER=`python -c "import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
          if [[ $PYVER != $PYTHON ]]; then
            exit 1;
          fi

      - name: run herasim tests
        run: |
          cd ../hera_sim
          python -m pytest -n auto
